// Reproducibly adapt hash-wasm for Workers' prohibition on runtime WASM compilation.
// Keep its upstream MIT banner and algorithm unchanged; import precompiled modules instead.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const source = readFileSync(new URL('../node_modules/hash-wasm/dist/argon2.umd.min.js', import.meta.url), 'utf8');
const binaries = [...source.matchAll(/name:"([^"]+)",data:"([^"]+)"/g)];
if (binaries.length !== 2 || !source.includes('WebAssembly.compile(I)')) throw new Error('Unexpected hash-wasm distribution; review adapter');
const directory = new URL('../src/auth/vendor/', import.meta.url);
mkdirSync(directory, { recursive: true });
for (const [, name, data] of binaries) writeFileSync(new URL(`${name}.wasm`, directory), Buffer.from(data, 'base64'));
const adapted = source.replace('WebAssembly.compile(I)', 'Promise.resolve(wasmModules[A.name])');
writeFileSync(new URL('argon2.js', directory), `// Generated by scripts/build-argon2.mjs. Do not edit.\nimport argon2 from './argon2.wasm';\nimport blake2b from './blake2b.wasm';\nconst wasmModules = { argon2, blake2b };\nconst exports = {}; const module = { exports };\n${adapted}\nexport const argon2id = exports.argon2id;\n`);
